package com.otto.app.push

import com.otto.app.nudge.NudgeAction
import com.otto.app.nudge.NudgeLevel
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The cross-repo contract, pinned against payloads the SERVER actually produced.
 *
 * Every map below was generated by running `nudgeData` / `cancelNudgeData` from
 * `otto-server/src/fcm/commands.ts` with the secret `s3cr3t`, and pasted here verbatim — signature
 * included. That is the point: the two ends of this contract live in different repositories, in
 * different languages, and nothing at build time checks one against the other. A field renamed on
 * the server, a value serialised differently, or a change to what the signature covers would
 * otherwise show up only as a nudge that silently never arrives on the owner's phone.
 *
 * If one of these fails, the fix is a conversation between the two repos, not a new expectation.
 */
class ServerPayloadContractTest {

    private val secret = "s3cr3t"

    private val serverNudge = mapOf(
        "v" to "1",
        "type" to "NUDGE",
        "nudgeId" to "rem_demo",
        "title" to "Email Teal",
        "body" to "Still open",
        "level" to "URGENT",
        "actions" to "DONE,SNOOZE",
        "snoozeMinutes" to "30",
        "expiresAtMillis" to "1751200000000",
        "ongoing" to "false",
        "sig" to "e64f004ad239d858d866b5eec1a4e1295d7694dc4cd4076c78ef4c2bbeec3c83",
    )

    private val serverCancelNudge = mapOf(
        "v" to "1",
        "type" to "CANCEL_NUDGE",
        "nudgeId" to "rem_demo",
        "sig" to "455f0cadabe32e13bd3e7eaa1997fc3c4e7f479a4c2988d6622f80e7c775bf73",
    )

    @Test
    fun serverNudge_passesTheSignatureGate() {
        // Verified before parsing on the real path, so a signature mismatch means the payload is
        // dropped without a single field ever being read — invisible from the server, which records
        // a successful send either way.
        assertTrue(HmacVerifier.verify(serverNudge, secret))
    }

    @Test
    fun serverNudge_parsesIntoExactlyWhatTheServerMeant() {
        val command = (CommandParser.parse(serverNudge) as ParseResult.Parsed).command as FcmCommand.Nudge
        assertEquals("rem_demo", command.nudgeId)
        assertEquals("Email Teal", command.title)
        assertEquals("Still open", command.body)
        assertEquals(NudgeLevel.URGENT, command.level)
        assertEquals(listOf(NudgeAction.DONE, NudgeAction.SNOOZE), command.actions)
        assertEquals(30, command.snoozeMinutes)
        assertEquals(1751200000000L, command.expiresAtMillis)
        assertEquals(false, command.ongoing)
    }

    @Test
    fun serverCancelNudge_verifiesAndParses() {
        assertTrue(HmacVerifier.verify(serverCancelNudge, secret))
        val command = (CommandParser.parse(serverCancelNudge) as ParseResult.Parsed).command as FcmCommand.CancelNudge
        assertEquals("rem_demo", command.nudgeId)
    }

    @Test
    fun theSignatureCoversTheNewFields()  {
        // The canonical form is generic over the map — every key except `sig`, sorted — which is
        // exactly what let two new command types and eight new fields land with no crypto change on
        // either side. This pins that genericity rather than trusting it: tamper with a field the
        // signature would have had to cover, and verification must fail.
        for (field in listOf("nudgeId", "title", "body", "level", "actions", "snoozeMinutes", "expiresAtMillis", "ongoing")) {
            val tampered = serverNudge.toMutableMap().apply { this[field] = "tampered" }
            assertTrue("tampering with $field must break the signature", !HmacVerifier.verify(tampered, secret))
        }
    }

    @Test
    fun anUnsignedNudgeIsRejected() {
        assertTrue(!HmacVerifier.verify(serverNudge.filterKeys { it != "sig" }, secret))
    }
}
