package com.otto.app.push

import com.otto.app.nudge.NudgeAction
import com.otto.app.nudge.NudgeLevel
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The cross-repo contract, pinned against payloads the SERVER actually produced.
 *
 * Every map below was generated by running `nudgeData` / `cancelNudgeData` from
 * `otto-server/src/fcm/commands.ts` with the secret `s3cr3t`, and pasted here verbatim — signature
 * included. That is the point: the two ends of this contract live in different repositories, in
 * different languages, and nothing at build time checks one against the other. A field renamed on
 * the server, a value serialised differently, or a change to what the signature covers would
 * otherwise show up only as a nudge that silently never arrives on the owner's phone.
 *
 * If one of these fails, the fix is a conversation between the two repos, not a new expectation.
 */
class ServerPayloadContractTest {

    private val secret = "s3cr3t"

    private val serverNudge = mapOf(
        "v" to "1",
        "type" to "NUDGE",
        "nudgeId" to "rem_demo",
        "title" to "Email Teal",
        "body" to "Still open",
        "level" to "URGENT",
        "actions" to "DONE,SNOOZE",
        "snoozeMinutes" to "30",
        "expiresAtMillis" to "1751200000000",
        "ongoing" to "false",
        "sig" to "e64f004ad239d858d866b5eec1a4e1295d7694dc4cd4076c78ef4c2bbeec3c83",
    )

    private val serverCancelNudge = mapOf(
        "v" to "1",
        "type" to "CANCEL_NUDGE",
        "nudgeId" to "rem_demo",
        "sig" to "455f0cadabe32e13bd3e7eaa1997fc3c4e7f479a4c2988d6622f80e7c775bf73",
    )

    /**
     * Generated by running `requestLocationData` from otto-server's `src/fcm/commands.ts`, and
     * pasted verbatim. Nothing at build time checks the two repos against each other, and this is
     * the type where that would hurt most: a location request has no fallback transport, so a field
     * the phone stopped recognising would leave the agent waiting on an answer that never comes.
     */
    private val serverRequestLocation = mapOf(
        "v" to "1",
        "type" to "REQUEST_LOCATION",
        "requestId" to "loc_demo",
        "maxAgeSeconds" to "300",
        "expiresAtMillis" to "1751200000000",
        "highAccuracy" to "true",
        "reason" to "work out when to leave for the dentist",
        "sig" to "4b6400648a1ec4696f2a90f0a7765b064a58785616a715da9ea1f2add9e9fc0d",
    )

    @Test
    fun serverRequestLocation_verifiesAndParses() {
        // The signature gate matters more here than anywhere else in this file. A REQUEST_LOCATION
        // handler downstream of an unverified parse would let anyone holding the FCM token ask this
        // phone where its owner is — which is why OttoFcmService verifies BEFORE parsing.
        assertTrue(HmacVerifier.verify(serverRequestLocation, secret))

        val command =
            (CommandParser.parse(serverRequestLocation) as ParseResult.Parsed).command as FcmCommand.RequestLocation
        assertEquals("loc_demo", command.requestId)
        // The server speaks SECONDS on the wire and the app works in millis — the exact place a
        // silent factor-of-1000 would hide.
        assertEquals(300_000L, command.maxAgeMillis)
        assertEquals(1751200000000L, command.expiresAtMillis)
        assertTrue(command.highAccuracy)
        assertEquals("work out when to leave for the dentist", command.reason)
    }

    @Test
    fun theSignatureCoversTheLocationFieldsToo() {
        for (field in listOf("requestId", "maxAgeSeconds", "expiresAtMillis", "highAccuracy", "reason")) {
            val tampered = serverRequestLocation.toMutableMap().apply { this[field] = "tampered" }
            assertTrue("tampering with $field must break the signature", !HmacVerifier.verify(tampered, secret))
        }
    }

    @Test
    fun serverNudge_passesTheSignatureGate() {
        // Verified before parsing on the real path, so a signature mismatch means the payload is
        // dropped without a single field ever being read — invisible from the server, which records
        // a successful send either way.
        assertTrue(HmacVerifier.verify(serverNudge, secret))
    }

    @Test
    fun serverNudge_parsesIntoExactlyWhatTheServerMeant() {
        val command = (CommandParser.parse(serverNudge) as ParseResult.Parsed).command as FcmCommand.Nudge
        assertEquals("rem_demo", command.nudgeId)
        assertEquals("Email Teal", command.title)
        assertEquals("Still open", command.body)
        assertEquals(NudgeLevel.URGENT, command.level)
        assertEquals(listOf(NudgeAction.DONE, NudgeAction.SNOOZE), command.actions)
        assertEquals(30, command.snoozeMinutes)
        assertEquals(1751200000000L, command.expiresAtMillis)
        assertEquals(false, command.ongoing)
    }

    @Test
    fun serverCancelNudge_verifiesAndParses() {
        assertTrue(HmacVerifier.verify(serverCancelNudge, secret))
        val command = (CommandParser.parse(serverCancelNudge) as ParseResult.Parsed).command as FcmCommand.CancelNudge
        assertEquals("rem_demo", command.nudgeId)
    }

    @Test
    fun theSignatureCoversTheNewFields()  {
        // The canonical form is generic over the map — every key except `sig`, sorted — which is
        // exactly what let two new command types and eight new fields land with no crypto change on
        // either side. This pins that genericity rather than trusting it: tamper with a field the
        // signature would have had to cover, and verification must fail.
        for (field in listOf("nudgeId", "title", "body", "level", "actions", "snoozeMinutes", "expiresAtMillis", "ongoing")) {
            val tampered = serverNudge.toMutableMap().apply { this[field] = "tampered" }
            assertTrue("tampering with $field must break the signature", !HmacVerifier.verify(tampered, secret))
        }
    }

    @Test
    fun anUnsignedNudgeIsRejected() {
        assertTrue(!HmacVerifier.verify(serverNudge.filterKeys { it != "sig" }, secret))
    }
}
